name: Docs
on: 
  pull_request:
    paths:
      - "docs/**"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Update pip
      run: python -m pip install -U pip
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v3
    - name: Install dependencies
      run: poetry install
    - name: Build docs
      run: poetry run sphinx-build .\docs\source\ .\docs\build\ --builder html
    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: "html_docs"
        path: docs/build/html/
  
