name: Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  test:

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Update pip
      run: python -m pip install -U pip
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v3
    - name: Install dependencies
      run: poetry install
    - name: Build
      run: poetry build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1.10
